version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: drtruck-mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=${DUMPS_PATH} --sql-mode=""
    restart: always
    volumes:
      - ../mysql/data/mysql/master:/var/lib/mysql
      - ../mysql/log/mysql/master:/var/lib/mysql_log
      - ../mysql/config/mysql/master:/etc/mysql/conf.d
      - ../mysql/install/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=autoparts
      - MYSQL_USER=autopart
      - MYSQL_PASSWORD=autopart
    ports:
      - 3306:3306